'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TimesheetModule

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hwelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hwelcome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sJDENo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sJDENo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sUsername As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ssFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssFullName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sSupvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sSupvName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tCrew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tCrew As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tJobCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tJobCost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Dd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dd1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddshift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddshift As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btoolbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btoolbox As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''boffschedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boffschedule As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTS As Global.System.Web.UI.WebControls.GridView
End Class
